config/routes.rb
Rails.application.routes.draw do
  mount RailsEventStore::Browser => '/res' if Rails.env.development?

  resources :dogs, only: [:index, :new, :create]

  resources :competitions, only: [:index, :new, :create, :show] do
    resources :journeys, only: [:index, :new, :create], module: :competitions
    resources :running_rounds, only: [:index, :show], module: :competitions
    member do
      post "publish"
    end
  end
  resources :journeys, only: [], module: :competitions do
    resources :trials, only: [:index, :new, :create]
  end
  resources :trials, only: [], module: :competitions do
    resources :rounds, only: [:index, :new, :create]
  end
  resources :rounds, only: [:index, :new, :create] do
    member do
      get "manage"
      post "enroll_dog"
      get "close"
    end
  end

  resources :scribesheets, only: [:show, :create] do
    member do
      post "record_refusal"
      post "record_fault"
      post "record_dog_time"
      post "record_elimination"
      post "finish"
    end
  end

  namespace :p do
    resources :competitions, only: [:show] do
      resources :registrations, only: [:new, :create]
    end
  end

  root "home#index"
end

app/controllers/competitions/journeys_controller.rb
module Competitions
  class JourneysController < ApplicationController
    def index
      @journeys = Competitions::Journey.where(competition_id: params[:competition_id])
    end

    def new
      @journey_id = SecureRandom.uuid
    end

    def create
      cmd = CompetitionManagement::AddJourneyToCompetition.new(
        competition_id: params[:competition_id],
        journey_id: params[:journey_id],
        happening_at: Date.parse(params[:date])
      )
      command_bus.call(cmd)

      redirect_to competition_journeys_path(params[:competition_id])
    end
  end
end

app/controllers/competitions/rounds_controller.rb
module Competitions
  class RoundsController < ApplicationController
    def index
      @rounds = Competitions::Round.where(trial_id: params[:trial_id])
    end

    def new
      @trial = Competitions::Trial.find(params[:trial_id])
      @round_id = SecureRandom.uuid
    end

    def create
      cmd = CompetitionManagement::AddRoundToCompetition.new(
        competition_id: params[:competition_id],
        trial_id: params[:trial_id],
        round_id: params[:round_id],
        name: params[:name]
      )
      command_bus.call(cmd)

      redirect_to trial_rounds_path(params[:trial_id])
    end
  end
end

app/controllers/competitions/running_rounds_controller.rb
module Competitions
  class RunningRoundsController < ApplicationController
    def index
      @rounds = Rounds::Round.where(competition_id: params[:competition_id])
    end

    def show
      @round = Rounds::Round.find_by_uid!(params[:id])
      @ranked_dogs = Rounds::Dog.where(round_uid: params[:id]).where(scribing_status: "finished").order(:rank)
    end
  end
end

app/controllers/competitions/trials_controller.rb
module Competitions
  class TrialsController < ApplicationController
    def index
      @trials = Competitions::Trial.where(journey_id: params[:journey_id])
    end

    def new
      @journey = Competitions::Journey.find(params[:journey_id])
      @trial_id = SecureRandom.uuid
    end

    def create
      cmd = CompetitionManagement::AddTrialToCompetition.new(
        competition_id: params[:competition_id],
        journey_id: params[:journey_id],
        trial_id: params[:trial_id],
        level: params[:level]
      )
      command_bus.call(cmd)

      redirect_to journey_trials_path(params[:journey_id])
    end
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  def index
    @competitions = Competitions::Competition.all
  end

  def show
    @competition = Competitions::Competition.find(params[:id])
  end

  def new
    @competition_id = SecureRandom.uuid
  end

  def create
    cmd = CompetitionManagement::AddCompetition.new(
      competition_id: params[:competition_id],
      name: params[:name]
    )
    command_bus.call(cmd)

    redirect_to competitions_path, notice: "Competition Added"
  end

  def publish
    cmd = CompetitionManagement::PublishCompetition.new(
      competition_id: params[:id]
    )
    command_bus.call(cmd)

    redirect_to competition_path(params[:id]), notice: "Competition Published"
  end
end

app/controllers/p/competitions_controller.rb
module P
  class CompetitionsController < ApplicationController
    def show
      @competition = Competitions::Competition.find(params[:id])
    end
  end
end

app/views/competitions/index.html.erb
<% content_for(:header) do %>
  Competitions
<% end %>

<% content_for(:actions) do %>
  <%= link_to 'New Competition', new_competition_path, class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
<% end %>

<div class="bg-white shadow overflow-hidden">
  <ul role="list" class="divide-y divide-gray-200">
    <% @competitions.each do |competition| %>
      <li>
        <a href="<%= competition_path(competition) %>" class="block hover:bg-gray-50">
          <div class="px-4 py-4 sm:px-6">
            <div class="flex items-center justify-between">
              <p class="text-sm font-medium text-indigo-600 truncate"><%= competition.name %></p>
              <div class="ml-2 flex-shrink-0 flex">
                <% if competition.status == "Draft" %>
                  <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800">Draft</p>
                <% elsif competition.status == "Published" %>
                  <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">Published</p>
                <% end %>
              </div>
            </div>
            <div class="mt-2 sm:flex sm:justify-between">
              <div class="sm:flex">
                <p class="flex items-center text-sm text-gray-500">
                  <!-- Heroicon name: solid/users -->
                  <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M10 6H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V8a2 2 0 00-2-2h-5m-4 0V5a2 2 0 114 0v1m-4 0a2 2 0 104 0m-5 8a2 2 0 100-4 2 2 0 000 4zm0 0c1.306 0 2.417.835 2.83 2M9 14a3.001 3.001 0 00-2.83 2M15 11h3m-3 4h2" />
                  </svg>
                  Open
                </p>
              </div>
              <div class="mt-2 flex items-center text-sm text-gray-500 sm:mt-0">
              </div>
            </div>
          </div>
        </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/competitions/new.html.erb
<% content_for(:header) do %>
  New Competition
<% end %>

<%= form_with url: competitions_path, method: :post do |form| %>
  <%= form.hidden_field :competition_id, :value => @competition_id %>
  <div class="pt-8">
    <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
      <div class="sm:col-span-3">
        <label for="first-name" class="block text-sm font-medium text-gray-700">
          Name
        </label>
        <div class="mt-1">
          <%= form.text_field :name, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border border-gray-800 px-3 py-2 rounded-md" %>
        </div>
      </div>
    </div>
  </div>
  <div class="pt-5">
    <div class="flex justify-start">
      <button type="button" class="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        Cancel
      </button>
      <%= form.submit "Save", class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
  </div>
<% end %>

app/views/competitions/show.html.erb
<div class="py-8 xl:py-10">
  <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 xl:max-w-5xl xl:grid xl:grid-cols-3">
    <div class="xl:col-span-2 xl:pr-8 xl:border-r xl:border-gray-200">
      <div>
        <div>
          <div class="md:flex md:items-center md:justify-between md:space-x-4 xl:border-b xl:pb-6">
            <div>
              <h1 class="text-2xl font-bold text-gray-900"><%= @competition.name %></h1>
              <p class="mt-2 text-sm text-gray-500">
                Open
              </p>
            </div>
            <div class="mt-4 flex space-x-3 md:mt-0">
              <button type="button" class="inline-flex justify-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900">
                <!-- Heroicon name: solid/pencil -->
                <svg class="-ml-1 mr-2 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                </svg>
                <span>Edit</span>
              </button>

              <%= link_to "Public View", p_competition_path(@competition.id), class: "inline-flex justify-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900" %>

              <% unless @competition.status == "Published" %>
                <%= link_to publish_competition_path(@competition.id),
                  {
                    data: { "turbo-method": :post },
                    class: "inline-flex justify-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900"
                  } do %>
                    <svg xmlns="http://www.w3.org/2000/svg" class="-ml-1 mr-2 h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" />
                    </svg>
                    <span>Publish</span>
                <% end %>
              <% end %>
            </div>
          </div>
          <aside class="mt-8 xl:hidden">
            <h2 class="sr-only">Details</h2>
            <div class="space-y-5">
              <div class="flex items-center space-x-2">
                <% if @competition.status == "Draft" %>
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-yellow-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                  </svg>
                  <span class="text-yellow-700 text-sm font-medium">Draft</span>
                <% elsif @competition.status == "Published" %>
                  <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">Published</p>
                <% end %>
              </div>
            </div>
            <div class="mt-6 border-t border-b border-gray-200 py-6 space-y-8">
              <div>
                <h2 class="text-sm font-medium text-gray-500">Judges</h2>
                <ul role="list" class="mt-3 space-y-3">
                  <li class="flex justify-start">
                    <a href="#" class="flex items-center space-x-3">
                      <div class="flex-shrink-0">
                        <img class="h-5 w-5 rounded-full" src="https://images.unsplash.com/photo-1520785643438-5bf77931f493?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=256&h=256&q=80" alt="">
                      </div>
                      <div class="text-sm font-medium text-gray-900">Eduardo Benz</div>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </aside>
        </div>
      </div>
      <section aria-labelledby="activity-title" class="mt-8 xl:mt-10">
        <div>
          <% if @competition.status == "Draft" %>
            <div class="pb-4">
              <h2 class="text-lg font-medium text-gray-900">Journeys</h2>
            </div>
            <div class="pt-6">
              <%= turbo_frame_tag :competition_journeys, src: competition_journeys_path(@competition) %>
            </div>
          <% elsif @competition.status == "Published" %>
            <div class="pt-6">
              <%= turbo_frame_tag :competition_running_rounds, src: competition_running_rounds_path(@competition) %>
            </div>
          <% end %>
        </div>
      </section>
    </div>
    <aside class="hidden xl:block xl:pl-8">
      <h2 class="sr-only">Details</h2>
      <div class="space-y-5">
        <div class="flex items-center space-x-2">
          <% if @competition.status == "Draft" %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-yellow-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
            </svg>
            <span class="text-yellow-700 text-sm font-medium">Draft</span>
          <% elsif @competition.status == "Published" %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" />
            </svg>
            <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">Published</p>
          <% end %>
        </div>
      </div>
      <div class="mt-6 border-t border-gray-200 py-6 space-y-8">
        <div>
          <h2 class="text-sm font-medium text-gray-500">Judges</h2>
          <ul role="list" class="mt-3 space-y-3">
            <li class="flex justify-start">
              <a href="#" class="flex items-center space-x-3">
                <div class="flex-shrink-0">
                  <img class="h-5 w-5 rounded-full" src="https://images.unsplash.com/photo-1520785643438-5bf77931f493?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=256&h=256&q=80" alt="">
                </div>
                <div class="text-sm font-medium text-gray-900">Eduardo Benz</div>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </aside>
  </div>
</div>