config/routes.rb
Rails.application.routes.draw do
  mount RailsEventStore::Browser => '/res' if Rails.env.development?

  resources :dogs, only: [:index, :new, :create]

  resources :competitions, only: [:index, :new, :create, :show] do
    resources :journeys, only: [:index, :new, :create], module: :competitions
    resources :running_rounds, only: [:index, :show], module: :competitions
    member do
      post "publish"
    end
  end
  resources :journeys, only: [], module: :competitions do
    resources :trials, only: [:index, :new, :create]
  end
  resources :trials, only: [], module: :competitions do
    resources :rounds, only: [:index, :new, :create]
  end
  resources :rounds, only: [:index, :new, :create] do
    member do
      get "manage"
      post "enroll_dog"
      get "close"
    end
  end

  resources :scribesheets, only: [:show, :create] do
    member do
      post "record_refusal"
      post "record_fault"
      post "record_dog_time"
      post "record_elimination"
      post "finish"
    end
  end

  namespace :p do
    resources :competitions, only: [:show] do
      resources :registrations, only: [:new, :create]
    end
  end

  root "home#index"
end

app/controllers/competitions/rounds_controller.rb
module Competitions
  class RoundsController < ApplicationController
    def index
      @rounds = Competitions::Round.where(trial_id: params[:trial_id])
    end

    def new
      @trial = Competitions::Trial.find(params[:trial_id])
      @round_id = SecureRandom.uuid
    end

    def create
      cmd = CompetitionManagement::AddRoundToCompetition.new(
        competition_id: params[:competition_id],
        trial_id: params[:trial_id],
        round_id: params[:round_id],
        name: params[:name]
      )
      command_bus.call(cmd)

      redirect_to trial_rounds_path(params[:trial_id])
    end
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def index
    @rounds = Rounds::Round.all
  end

  def new
    @round_id = SecureRandom.uuid
  end

  def create
    cmd = RoundManagement::AddRound.new(
      round_id: params[:round_id],
      name: params[:name]
    )
    command_bus.call(cmd)

    redirect_to rounds_path, notice: "Round Added"
  end

  def manage
    @round = Rounds::Round.find_by_uid!(params[:id])
    @enrolled_dogs = Rounds::Dog.where(round_uid: params[:id])
    @dogs = Dogs::Dog.all
  end

  def enroll_dog
    cmd = RoundManagement::EnrollDogToRound.new(
      round_id: params[:id],
      dog_id: params[:dog_id]
    )
    command_bus.call(cmd)

    redirect_to manage_round_path(id:  params[:id]), notice: "Dog Enrolled"
  end

  def close
    cmd = RoundManagement::CloseRound.new(
      round_id: params[:id]
    )
    command_bus.call(cmd)

    redirect_to manage_round_path(id:  params[:id]), notice: "Round Closed"
  end
end

app/views/rounds/index.html.erb
<% content_for(:header) do %>
  Rounds
<% end %>

<% content_for(:actions) do %>
  <%= link_to 'New Round', new_round_path, class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
<% end %>

<table class="w-full">
  <thead>
    <tr>
      <th class="text-left py-2">Name</th>
      <th class="text-left py-2">Actions</th>
    </tr>
  </thead>

  <tbody>
  <% @rounds.each do |round| %>
    <tr class="border-t">
      <td class="py-2"><%= round.name %></td>
      <td class="py-2">
        <%= link_to 'Manage', manage_round_path(id: round.uid), class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/rounds/manage.html.erb
<div class="pb-5 border-b border-gray-200">
  <div class="-ml-2 -mt-2 flex flex-wrap items-baseline">
    <h3 class="ml-2 mt-2 text-lg leading-6 font-medium text-gray-900">
      <%= @round.name %>
    </h3>
    <p class="ml-2 mt-1 text-sm text-gray-500 truncate"><%= @round.enrolled_dogs_count %> enrolled dogs</p>
    <% if @round.status == "open" %>
      <span class="ml-2 inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-green-100 text-green-800">
        open
      </span>
    <% elsif @round.status == "closed" %>
      <span class="ml-2 inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-red-100 text-red-800">
        closed
      </span>
    <% end %>
  </div>

  <% if @round.status == "open" %>
    <table class="w-full">
      <thead>
        <tr>
          <th class="text-left py-2">Name</th>
          <th class="text-left py-2">Actions</th>
        </tr>
      </thead>

      <tbody>
      <% @dogs.each do |dog| %>
        <tr class="border-t">
          <td class="py-2"><%= dog.name %></td>
          <td class="py-2">
            <% if @enrolled_dogs.find {|enrolled_dog| enrolled_dog.uid == dog.uid } %>
              <span>Enrolled</span>
            <% else %>
              <%= link_to "Enroll", enroll_dog_round_path(id: @round.uid, dog_id: dog.uid),
                {
                  data: { "turbo-method": :post },
                  class: "text-blue-500 hover:underline"
                }
              %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% elsif @round.status == "closed" %>
    <table class="w-full">
      <thead>
        <tr>
          <th class="text-left py-2">Name</th>
          <th class="text-left py-2">Actions</th>
        </tr>
      </thead>

      <tbody>
      <% @enrolled_dogs.each do |dog| %>
        <tr class="border-t">
          <td class="py-2"><%= dog.name %></td>
          <td class="py-2">
            <% if dog.scribing_status == "in_progress" %>
              <%= link_to "Continue scribing", scribesheet_path(dog.scribesheet_id),
                { class: "text-blue-500 hover:underline" }
              %>
            <% elsif dog.scribing_status == "finished" %>
              Scribing Finished
            <% else %>
              <%= link_to "Scribe", scribesheets_path(
                  scribesheet_id: SecureRandom.uuid,
                  round_id: @round.uid,
                  dog_id: dog.uid
                ),
                {
                  data: { "turbo-method": :post },
                  class: "text-blue-500 hover:underline"
                }
              %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>

  <%= link_to "Close", close_round_path(id: @round.uid), class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
</div>

app/views/rounds/new.html.erb
<% content_for(:header) do %>
  New Round
<% end %>

<%= form_with url: rounds_path, method: :post do |form| %>
  <%= form.hidden_field :round_id, :value => @round_id %>
  <div class="pt-8">
    <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
      <div class="sm:col-span-3">
        <label for="first-name" class="block text-sm font-medium text-gray-700">
          Name
        </label>
        <div class="mt-1">
          <%= form.text_field :name, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border border-gray-800 px-3 py-2 rounded-md" %>
        </div>
      </div>
    </div>
  </div>
  <div class="pt-5">
    <div class="flex justify-start">
      <button type="button" class="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        Cancel
      </button>
      <%= form.submit "Save", class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
  </div>
<% end %>