config/routes.rb
Rails.application.routes.draw do
  mount RailsEventStore::Browser => '/res' if Rails.env.development?

  resources :dogs, only: [:index, :new, :create]

  resources :competitions, only: [:index, :new, :create, :show] do
    resources :journeys, only: [:index, :new, :create], module: :competitions
    resources :running_rounds, only: [:index, :show], module: :competitions
    member do
      post "publish"
    end
  end
  resources :journeys, only: [], module: :competitions do
    resources :trials, only: [:index, :new, :create]
  end
  resources :trials, only: [], module: :competitions do
    resources :rounds, only: [:index, :new, :create]
  end
  resources :rounds, only: [:index, :new, :create] do
    member do
      get "manage"
      post "enroll_dog"
      get "close"
    end
  end

  resources :scribesheets, only: [:show, :create] do
    member do
      post "record_refusal"
      post "record_fault"
      post "record_dog_time"
      post "record_elimination"
      post "finish"
    end
  end

  namespace :p do
    resources :competitions, only: [:show] do
      resources :registrations, only: [:new, :create]
    end
  end

  root "home#index"
end

app/controllers/scribesheets_controller.rb
class ScribesheetsController < ApplicationController
  def create
    cmd = Scribing::StartScribing.new(
      scribesheet_id: params[:scribesheet_id],
      round_id: params[:round_id],
      dog_id: params[:dog_id],
    )
    command_bus.call(cmd)

    redirect_to scribesheet_path(params[:scribesheet_id])
  end

  def show
    @enrolled_dog = Rounds::Dog.find_by(scribesheet_id: params[:id])
    @round = Rounds::Round.find_by(uid: @enrolled_dog.round_uid)
  end

  def record_refusal
    cmd = Scribing::RecordRefusal.new(
      scribesheet_id: params[:scribesheet_id]
    )
    command_bus.call(cmd)

    redirect_to scribesheet_path(params[:scribesheet_id])
  end

  def record_fault
    cmd = Scribing::RecordFault.new(
      scribesheet_id: params[:scribesheet_id]
    )
    command_bus.call(cmd)

    redirect_to scribesheet_path(params[:scribesheet_id])
  end

  def record_elimination
    cmd = Scribing::RecordElimination.new(
      scribesheet_id: params[:scribesheet_id]
    )
    command_bus.call(cmd)

    redirect_to scribesheet_path(params[:scribesheet_id])
  end

  def record_dog_time
    cmd = Scribing::RecordDogTime.new(
      scribesheet_id: params[:scribesheet_id],
      seconds: params[:seconds].to_i,
      hundredths: params[:hundredths].to_i
    )
    command_bus.call(cmd)

    redirect_to scribesheet_path(params[:scribesheet_id])
  end

  def finish
    cmd = Scribing::FinishScribing.new(
      scribesheet_id: params[:scribesheet_id]
    )
    command_bus.call(cmd)

    enrolled_dog = Rounds::Dog.find_by(scribesheet_id: params[:scribesheet_id])

    redirect_to manage_round_path(id: enrolled_dog.round_uid)
  rescue Scribing::Scribesheet::DogTimeNotRecorded
    redirect_to scribesheet_path(params[:scribesheet_id]), alert: "You must record dog's time before finish"
  end
end

app/views/scribesheets/show.html.erb
<div class="pb-5 border-b border-gray-200">
  <div class="-ml-2 -mt-2 flex flex-wrap items-baseline">
    <h3 class="ml-2 mt-2 text-lg leading-6 font-medium text-gray-900">
     <%= @round.name %> / <%= @enrolled_dog.name %>
    </h3>
  </div>
  <table class="w-full">
    <tbody>
      <tr class="border-t">
        <td class="py-2"><%= @enrolled_dog.refusals_count %> Refusal</td>
        <td class="py-2">
          <%= link_to "Record a refusal", record_refusal_scribesheet_path(scribesheet_id: @enrolled_dog.scribesheet_id),
            {
              data: { "turbo-method": :post },
              class: "text-blue-500 hover:underline"
            }
          %>
        </td>
      </tr>
      <tr class="border-t">
        <td class="py-2"><%= @enrolled_dog.faults_count %> Faults</td>
        <td class="py-2">
          <%= link_to "Record a fault", record_fault_scribesheet_path(scribesheet_id: @enrolled_dog.scribesheet_id),
            {
              data: { "turbo-method": :post },
              class: "text-blue-500 hover:underline"
            }
          %>
        </td>
      </tr>
      <tr class="border-t">
        <td class="py-2">Eliminated: <%= @enrolled_dog.eliminated ? "Yes" : "No" %></td>
        <td class="py-2">
          <% unless @enrolled_dog.eliminated %>
            <%= link_to "Record elimination", record_elimination_scribesheet_path(scribesheet_id: @enrolled_dog.scribesheet_id),
              {
                data: { "turbo-method": :post },
                class: "text-blue-500 hover:underline"
              }
            %>
          <% end %>
        </td>
      </tr>
      <tr class="border-t">
        <td class="py-2"></td>
        <td class="py-2">
          <% if @enrolled_dog.dog_time %>
            <strong>Dog's Time</strong>: <%= @enrolled_dog.dog_time %>
          <% else %>
            <%= form_with url: record_dog_time_scribesheet_path, method: :post do |form| %>
              <%= form.hidden_field :scribesheet_id, value: @enrolled_dog.scribesheet_id %>
              <div class="sm:grid sm:grid-cols-4">
                <%= form.number_field :seconds, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border border-gray-800 px-3 py-2 rounded-md" %>
                <%= form.number_field :hundredths, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border border-gray-800 px-3 py-2 rounded-md" %>
                <%= form.submit "Record Dog's Time", class: "sm:col-span-2 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
              </div>
            <% end %>
          <% end %>
        </td>
      </tr>
      <tr class="border-t">
        <td class="py-2"></td>
        <td class="py-2">
          <%= link_to "Finish", finish_scribesheet_path(scribesheet_id: @enrolled_dog.scribesheet_id),
            {
              data: { "turbo-method": :post },
              class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            }
          %>
        </td>
      </tr>
    </tbody>
  </table>
</div>