config/routes.rb
Rails.application.routes.draw do
  mount RailsEventStore::Browser => '/res' if Rails.env.development?

  resources :dogs, only: [:index, :new, :create]

  resources :competitions, only: [:index, :new, :create, :show] do
    resources :journeys, only: [:index, :new, :create], module: :competitions
    resources :running_rounds, only: [:index, :show], module: :competitions
    member do
      post "publish"
    end
  end
  resources :journeys, only: [], module: :competitions do
    resources :trials, only: [:index, :new, :create]
  end
  resources :trials, only: [], module: :competitions do
    resources :rounds, only: [:index, :new, :create]
  end
  resources :rounds, only: [:index, :new, :create] do
    member do
      get "manage"
      post "enroll_dog"
      get "close"
    end
  end

  resources :scribesheets, only: [:show, :create] do
    member do
      post "record_refusal"
      post "record_fault"
      post "record_dog_time"
      post "record_elimination"
      post "finish"
    end
  end

  namespace :p do
    resources :competitions, only: [:show] do
      resources :registrations, only: [:new, :create]
    end
  end

  root "home#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def event_store
    Rails.configuration.event_store
  end

  def command_bus
    Rails.configuration.command_bus
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer class="bg-gray-100" aria-labelledby="footer-heading">
  <h2 id="footer-heading" class="sr-only">Footer</h2>
  <div class="max-w-6xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
    <div class="xl:grid xl:grid-cols-6 xl:gap-8">
      <div class="space-y-8 xl:col-span-3">
        <p class="text-gray-500 text-base">
          AgilityOn
        </p>
      </div>
      <div class="mt-12 grid grid-cols-1 gap-8 xl:mt-0 xl:col-span-3">
        <div class="md:grid md:grid-cols-3 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
              Links #1
            </h3>
            <ul role="list" class="mt-4 space-y-4">
              <li>
                <%= link_to "Clubs", "#", class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
              Links #2
            </h3>
            <ul role="list" class="mt-4 space-y-4">
              <li>
                <%= link_to "Dogs", dogs_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
              Links #3
            </h3>
            <ul role="list" class="mt-4 space-y-4">
              <li>
                <%= link_to "Rounds", "#", class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/application/_top_navigation.html.erb
<nav class="bg-gray-800">
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <h1 class="text-gray-600 uppercase tracking-tight font-bold">
            AgilityOn
          </h1>
        </div>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline space-x-4">
            <%= link_to "Competitions", competitions_path, class: "px-3 py-2 rounded-md text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
            <%= link_to "Dogs", dogs_path, class: "px-3 py-2 rounded-md text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
            <%= link_to "Rounds", rounds_path, class: "px-3 py-2 rounded-md text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>